version: '3.8'

services:
  climingo-api:
    image: climingo/climingo:${TAG} # Spring Boot 애플리케이션 Docker 이미지
    container_name: climingo-api
    environment:
      - JASYPT_PASSWORD=${JASYPT_PASSWORD}
      - VERSION=${TAG}
      - BUILDTIME=${BUILDTIME}
    ports:
      - "8080:8080"